export const colors = {
  background: "#F6F2E9",
  surface: "#FFFDF8",
  text: "#292621",
  primary: "#48624D",
  accent: "#B76642",
  muted: "#8B867B",
  divider: "#DDD7CB",
  descriptorSurface: "#EEE9DE",
  detailSurface: "#F0EBE1",
  flavorPink: "#F4E5E8",
  flavorPeach: "#FBE7D7",
  flavorGreen: "#ECEFD9",
  bag: "#EDE5D5",
  bagEdge: "#D5CCBA",
  bagLandscape: "#BCC1AC",
};
